import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * BackendConnectionError - Component to display when backend is not available
 */
import { Alert, AlertDescription, AlertTitle } from './ui/alert';
import { Button } from './ui/button';
import { AlertCircle, RefreshCw, ExternalLink } from 'lucide-react';
import { EXTERNAL_URLS } from '../config/api';
export function BackendConnectionError({ onRetry, projectId }) {
    // Get projectId from environment variables if not provided
    const envProjectId = import.meta.env.VITE_SUPABASE_URL?.split('//')[1]?.split('.')[0];
    const displayProjectId = projectId || envProjectId;
    return (_jsx("div", { className: "min-h-screen bg-background p-4 flex items-center justify-center", children: _jsxs("div", { className: "max-w-2xl w-full space-y-4", children: [_jsxs(Alert, { variant: "destructive", className: "border-red-200 bg-red-50 dark:bg-red-950/20", children: [_jsx(AlertCircle, { className: "h-5 w-5" }), _jsx(AlertTitle, { className: "text-lg", children: "Backend Connection Failed" }), _jsxs(AlertDescription, { className: "mt-2 space-y-3", children: [_jsx("p", { children: "The application cannot connect to the backend server. This usually means the Supabase Edge Function is not deployed or not responding." }), _jsxs("div", { className: "bg-red-100 dark:bg-red-900/30 p-3 rounded-md text-sm", children: [_jsx("p", { className: "font-semibold mb-1", children: "Common causes:" }), _jsxs("ul", { className: "list-disc list-inside space-y-1 ml-2", children: [_jsx("li", { children: "Backend Edge Function not deployed" }), _jsx("li", { children: "Supabase project is paused or inactive" }), _jsx("li", { children: "Network connectivity issues" }), _jsx("li", { children: "Invalid API keys or project configuration" })] })] }), displayProjectId && (_jsxs("div", { className: "bg-blue-50 dark:bg-blue-950/20 p-3 rounded-md text-sm border border-blue-200 dark:border-blue-800", children: [_jsx("p", { className: "font-semibold mb-1", children: "\uD83D\uDD27 How to fix:" }), _jsxs("ol", { className: "list-decimal list-inside space-y-2 ml-2", children: [_jsxs("li", { children: ["Open your Supabase dashboard for project: ", _jsx("code", { className: "bg-blue-100 dark:bg-blue-900/40 px-1 py-0.5 rounded", children: displayProjectId })] }), _jsx("li", { children: "Navigate to Edge Functions" }), _jsxs("li", { children: ["Deploy the ", _jsx("code", { className: "bg-blue-100 dark:bg-blue-900/40 px-1 py-0.5 rounded", children: "make-server-228aa219" }), " function"] }), _jsx("li", { children: "Ensure the function is running and healthy" })] })] })), _jsxs("div", { className: "flex gap-2 pt-2", children: [onRetry && (_jsxs(Button, { onClick: onRetry, size: "sm", className: "gap-2", children: [_jsx(RefreshCw, { className: "h-4 w-4" }), "Retry Connection"] })), displayProjectId && (_jsxs(Button, { variant: "outline", size: "sm", className: "gap-2", onClick: () => window.open(EXTERNAL_URLS.SUPABASE_DASHBOARD(displayProjectId), '_blank'), children: [_jsx(ExternalLink, { className: "h-4 w-4" }), "Open Supabase Dashboard"] }))] })] })] }), _jsx("div", { className: "text-center text-sm text-muted-foreground", children: _jsx("p", { children: "Need help? Check the browser console for detailed error messages." }) })] }) }));
}
