// Centralized icon imports for the application
import {
  CreditCard,
  Calculator,
  Zap,
  Building,
  Shield,
  Globe,
  Smartphone,
  Laptop,
  Database,
  Lock,
  Key,
  Wallet,
  TrendingUp,
  BarChart3,
  PieChart,
  LineChart,
  Activity,
  Target,
  Rocket,
  Star,
  Heart,
  DollarSign,
  Euro,
  Bitcoin,
  Banknote,
  Coins,
  Receipt,
  FileText,
  Settings,
  Cog,
  Wrench,
  Package,
  Truck,
  Plane,
  Ship,
  Car,
  Bike,
  Bus,
  Train,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Plus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  User,
  Users,
  History,
  UserCheck,
  Download,
  RefreshCw,
  Copy,
  Mail,
  Calendar,
  Clock,
  CheckCircle,
  XCircle,
  AlertCircle,
  Info,
  Home,
  LogOut,
  ChevronLeft,
  ChevronRight,
  Save,
  X,
  Loader2
} from 'lucide-react';

// Simulator icon mapping
export const SIMULATOR_ICON_MAP: Record<string, React.ReactNode> = {
  CreditCard: <CreditCard className="h-8 w-8" />,
  Calculator: <Calculator className="h-8 w-8" />,
  Zap: <Zap className="h-8 w-8" />,
  Building: <Building className="h-8 w-8" />,
  Shield: <Shield className="h-8 w-8" />,
  Globe: <Globe className="h-8 w-8" />,
  Smartphone: <Smartphone className="h-8 w-8" />,
  Laptop: <Laptop className="h-8 w-8" />,
  Database: <Database className="h-8 w-8" />,
  Lock: <Lock className="h-8 w-8" />,
  Key: <Key className="h-8 w-8" />,
  Wallet: <Wallet className="h-8 w-8" />,
  TrendingUp: <TrendingUp className="h-8 w-8" />,
  BarChart3: <BarChart3 className="h-8 w-8" />,
  PieChart: <PieChart className="h-8 w-8" />,
  LineChart: <LineChart className="h-8 w-8" />,
  Activity: <Activity className="h-8 w-8" />,
  Target: <Target className="h-8 w-8" />,
  Rocket: <Rocket className="h-8 w-8" />,
  Star: <Star className="h-8 w-8" />,
  Heart: <Heart className="h-8 w-8" />,
  DollarSign: <DollarSign className="h-8 w-8" />,
  Euro: <Euro className="h-8 w-8" />,
  Bitcoin: <Bitcoin className="h-8 w-8" />,
  Banknote: <Banknote className="h-8 w-8" />,
  Coins: <Coins className="h-8 w-8" />,
  Receipt: <Receipt className="h-8 w-8" />,
  FileText: <FileText className="h-8 w-8" />,
  Settings: <Settings className="h-8 w-8" />,
  Cog: <Cog className="h-8 w-8" />,
  Wrench: <Wrench className="h-8 w-8" />,
  Package: <Package className="h-8 w-8" />,
  Truck: <Truck className="h-8 w-8" />,
  Plane: <Plane className="h-8 w-8" />,
  Ship: <Ship className="h-8 w-8" />,
  Car: <Car className="h-8 w-8" />,
  Bike: <Bike className="h-8 w-8" />,
  Bus: <Bus className="h-8 w-8" />,
  Train: <Train className="h-8 w-8" />
};

// Small icon mapping for admin interface
export const SIMULATOR_ICON_MAP_SMALL: Record<string, React.ReactNode> = {
  CreditCard: <CreditCard className="h-4 w-4" />,
  Calculator: <Calculator className="h-4 w-4" />,
  Zap: <Zap className="h-4 w-4" />,
  Building: <Building className="h-4 w-4" />,
  Shield: <Shield className="h-4 w-4" />,
  Globe: <Globe className="h-4 w-4" />,
  Smartphone: <Smartphone className="h-4 w-4" />,
  Laptop: <Laptop className="h-4 w-4" />,
  Database: <Database className="h-4 w-4" />,
  Lock: <Lock className="h-4 w-4" />,
  Key: <Key className="h-4 w-4" />,
  Wallet: <Wallet className="h-4 w-4" />,
  TrendingUp: <TrendingUp className="h-4 w-4" />,
  BarChart3: <BarChart3 className="h-4 w-4" />,
  PieChart: <PieChart className="h-4 w-4" />,
  LineChart: <LineChart className="h-4 w-4" />,
  Activity: <Activity className="h-4 w-4" />,
  Target: <Target className="h-4 w-4" />,
  Rocket: <Rocket className="h-4 w-4" />,
  Star: <Star className="h-4 w-4" />,
  Heart: <Heart className="h-4 w-4" />,
  DollarSign: <DollarSign className="h-4 w-4" />,
  Euro: <Euro className="h-4 w-4" />,
  Bitcoin: <Bitcoin className="h-4 w-4" />,
  Banknote: <Banknote className="h-4 w-4" />,
  Coins: <Coins className="h-4 w-4" />,
  Receipt: <Receipt className="h-4 w-4" />,
  FileText: <FileText className="h-4 w-4" />,
  Settings: <Settings className="h-4 w-4" />,
  Cog: <Cog className="h-4 w-4" />,
  Wrench: <Wrench className="h-4 w-4" />,
  Package: <Package className="h-4 w-4" />,
  Truck: <Truck className="h-4 w-4" />,
  Plane: <Plane className="h-4 w-4" />,
  Ship: <Ship className="h-4 w-4" />,
  Car: <Car className="h-4 w-4" />,
  Bike: <Bike className="h-4 w-4" />,
  Bus: <Bus className="h-4 w-4" />,
  Train: <Train className="h-4 w-4" />
};

// Export all icons for direct use
export {
  CreditCard,
  Calculator,
  Zap,
  Building,
  Shield,
  Globe,
  Smartphone,
  Laptop,
  Database,
  Lock,
  Key,
  Wallet,
  TrendingUp,
  BarChart3,
  PieChart,
  LineChart,
  Activity,
  Target,
  Rocket,
  Star,
  Heart,
  DollarSign,
  Euro,
  Bitcoin,
  Banknote,
  Coins,
  Receipt,
  FileText,
  Settings,
  Cog,
  Wrench,
  Package,
  Truck,
  Plane,
  Ship,
  Car,
  Bike,
  Bus,
  Train,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Plus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  User,
  Users,
  History,
  UserCheck,
  Download,
  RefreshCw,
  Copy,
  Mail,
  Calendar,
  Clock,
  CheckCircle,
  XCircle,
  AlertCircle,
  Info,
  Home,
  LogOut,
  ChevronLeft,
  ChevronRight,
  Save,
  X,
  Loader2
};
